### ISSUE TITLE
Code Access

### ISSUE THREAD

**Issue by AlexHu123** [YunseokJANG/amc-gan#2]
I have read your paper, and feel deeply inspired! It's really good work~ 
Would it be possible for you to release the code, even it may not be very complete? (due to bad airline)
Thank you for taking the time to read this issue from your hectic work~~~

**Comment by YunseokJANG** [comment]
Hi @AlexHu123 ,
thanks for your interest in our project and sorry for the delay. I honestly put this project in priority, but I am totally out of time nowadays. I will try my best to upload once I get some spare times. But again, sorry for the delay.

Sincerely,
- Yunseok
